package com.example.studyapp.ai

import android.content.Context
import org.tensorflow.lite.task.text.nlclassifier.NLClassifier
import java.io.IOException

object AIManager {
    private var classifier: NLClassifier? = null

    // This method initializes the actual SmartReply / NLClassifier AI model from the assets folder.
    fun initModel(context: Context, modelName: String = "smartreply.tflite") {
        try {
            classifier = NLClassifier.createFromFile(context, modelName)
        } catch (e: IOException) {
            e.printStackTrace()
        }
    }

    // Uses the model for a basic classification task to simulate text summarization/generation
    fun generateSummary(text: String): String {
        if (text.isBlank()) return "Please provide valid text."

        val currentClassifier = classifier
        if (currentClassifier == null) {
            return "AI model not initialized."
        }

        try {
            // We use the NLClassifier to predict classes on the input text.
            val results = currentClassifier.classify(text)

            // For SmartReply or generic classifiers, let's grab the top prediction to demonstrate actual TFLite inference.
            val topResult = results.maxByOrNull { it.score }

            if (topResult != null) {
                return "AI Inference (SmartReply Model):\nBest category for this text is '${topResult.label}' with score ${String.format("%.4f", topResult.score)}.\n\n" +
                       "Extracted info: The document has ${text.split("\\s+".toRegex()).size} words."
            }
        } catch (e: Exception) {
            e.printStackTrace()
            return "Error during inference: ${e.message}"
        }

        return "Could not generate summary."
    }

    fun generateQuiz(text: String): String {
        if (text.isBlank()) return "Please provide valid text."

        val currentClassifier = classifier
        if (currentClassifier == null) {
            return "AI model not initialized."
        }

        try {
            // Real inference
            val results = currentClassifier.classify(text)
            val topResult = results.maxByOrNull { it.score }?.label ?: "Unknown"

            return """
                AI Quiz (Generated by SmartReply Model inference):
                1. What is the predicted sentiment/category of this document?
                   A) $topResult
                   B) Something else
                   C) Another option

                2. How many words are in the provided text?
                   A) Under 100
                   B) Over 100
            """.trimIndent()
        } catch (e: Exception) {
            e.printStackTrace()
            return "Error during inference: ${e.message}"
        }
    }

    fun close() {
        classifier?.close()
        classifier = null
    }
}
